In [5]:
import tensorflow as tf
import numpy as np
import matplotlib as plot
mnist = tf.keras.datasets.mnist

In [7]:
# Testing the dataset
(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0


11493376/11490434 [==============================] - 6s 0us/step
[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 ...

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]

In [26]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(512, activation=tf.nn.relu),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation=tf.nn.softmax)
])
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
37216/60000 [=================>............] - ETA: 11s - loss: 0.2652 - acc: 0.9196 ETA: 11s - loss: 0.2676

KeyboardInterrupt: 

In [11]:
model.evaluate(x_test, y_test)

10000/10000 [==============================] - 1s 107us/step


[0.06319925915937638, 0.9809]

In [13]:
learning_rate = 0.01
training_iteration = 30
batch_size = 100
display_step = 2

In [17]:
# Setup network input and output
x = tf.placeholder("float", [None, 784])
y = tf.placeholder("float", [None, 10])

#create Model
W = tf.Variable(tf.zeros([784, 10]))
b = tf.Variable(tf.zeros([10]))

In [19]:
with tf.name_scope("Wx_b") as scope:
    
    model = tf.nn.softmax(tf.matmul(x, W) + b)
    
w_h = tf.summary.histogram("weights", W)
b_h = tf.summary.histogram("biases", b)

In [24]:
with tf.name_scope("cost_function") as scope:
    cost_function = -tf.reduce_sum(y*tf.log(model))
    tf.summary.scalar("cost_function", cost_function)
    
with tf.name_scope("train") as scope:
    optimizer = tf.train.GradientDescentOptimizer(learning_rate).minimize(cost_function)
    
init = tf.global_variables_initializer()
merged_summary_op = tf.summary.merge_all


In [25]:
with tf.Session() as sess:
    sess.run(init)
    
    summary.writer = tf.train.SummaryWriter('/logs', graph_def=sess.graph_def)
    
    for interation in range(training_iteration):
        avg_cost = 0
        total_batch = int(mnist.train.num_examples/batch_size)
        
        for i in range(total_batch):
            batch_xs, batch_ys = mnist.train.next_batch(batch_size)
            sess.run(optimizer, feed_dict={x: batch_xs, y: batch_ys})
                        

InvalidArgumentError: Cannot assign a device for operation 'Adam_1/iterations/IsInitialized/VarIsInitializedOp': Could not satisfy explicit device specification '' because the node was colocated with a group of nodes that required incompatible device '/device:GPU:1'
Colocation Debug Info:
Colocation group had the following types and devices: 
VarHandleOp: CPU 
AssignVariableOp: CPU 
VarIsInitializedOp: CPU 
ReadVariableOp: CPU 
AssignAddVariableOp: CPU 

Colocation members and user-requested devices:
  Adam_1/iterations (VarHandleOp) 
  Adam_1/iterations/IsInitialized/VarIsInitializedOp (VarIsInitializedOp) 
  Adam_1/iterations/Assign (AssignVariableOp) 
  Adam_1/iterations/Read/ReadVariableOp (ReadVariableOp) 
  training_1/Adam/AssignAddVariableOp (AssignAddVariableOp) /device:GPU:1
  training_1/Adam/ReadVariableOp (ReadVariableOp) /device:GPU:1
  training_1/Adam/Cast/ReadVariableOp (ReadVariableOp) 
  VarIsInitializedOp_21 (VarIsInitializedOp) /device:GPU:1

	 [[Node: Adam_1/iterations/IsInitialized/VarIsInitializedOp = VarIsInitializedOp[](Adam_1/iterations)]]

Caused by op 'Adam_1/iterations/IsInitialized/VarIsInitializedOp', defined at:
  File "c:\users\adr\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\adr\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\users\adr\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "c:\users\adr\appdata\local\programs\python\python36\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "c:\users\adr\appdata\local\programs\python\python36\lib\site-packages\ipykernel\kernelapp.py", line 486, in start
    self.io_loop.start()
  File "c:\users\adr\appdata\local\programs\python\python36\lib\site-packages\tornado\platform\asyncio.py", line 132, in start
    self.asyncio_loop.run_forever()
  File "c:\users\adr\appdata\local\programs\python\python36\lib\asyncio\base_events.py", line 422, in run_forever
    self._run_once()
  File "c:\users\adr\appdata\local\programs\python\python36\lib\asyncio\base_events.py", line 1434, in _run_once
    handle._run()
  File "c:\users\adr\appdata\local\programs\python\python36\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "c:\users\adr\appdata\local\programs\python\python36\lib\site-packages\tornado\platform\asyncio.py", line 122, in _handle_events
    handler_func(fileobj, events)
  File "c:\users\adr\appdata\local\programs\python\python36\lib\site-packages\tornado\stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "c:\users\adr\appdata\local\programs\python\python36\lib\site-packages\zmq\eventloop\zmqstream.py", line 450, in _handle_events
    self._handle_recv()
  File "c:\users\adr\appdata\local\programs\python\python36\lib\site-packages\zmq\eventloop\zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
  File "c:\users\adr\appdata\local\programs\python\python36\lib\site-packages\zmq\eventloop\zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "c:\users\adr\appdata\local\programs\python\python36\lib\site-packages\tornado\stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "c:\users\adr\appdata\local\programs\python\python36\lib\site-packages\ipykernel\kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "c:\users\adr\appdata\local\programs\python\python36\lib\site-packages\ipykernel\kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "c:\users\adr\appdata\local\programs\python\python36\lib\site-packages\ipykernel\kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "c:\users\adr\appdata\local\programs\python\python36\lib\site-packages\ipykernel\ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "c:\users\adr\appdata\local\programs\python\python36\lib\site-packages\ipykernel\zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "c:\users\adr\appdata\local\programs\python\python36\lib\site-packages\IPython\core\interactiveshell.py", line 2662, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "c:\users\adr\appdata\local\programs\python\python36\lib\site-packages\IPython\core\interactiveshell.py", line 2785, in _run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "c:\users\adr\appdata\local\programs\python\python36\lib\site-packages\IPython\core\interactiveshell.py", line 2901, in run_ast_nodes
    if self.run_code(code, result):
  File "c:\users\adr\appdata\local\programs\python\python36\lib\site-packages\IPython\core\interactiveshell.py", line 2961, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-10-cadc49da41a0>", line 9, in <module>
    metrics=['accuracy'])
  File "c:\users\adr\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\training\checkpointable\base.py", line 364, in _method_wrapper
    method(self, *args, **kwargs)
  File "c:\users\adr\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\keras\engine\training.py", line 182, in compile
    self.optimizer = optimizers.get(optimizer)
  File "c:\users\adr\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\keras\optimizers.py", line 818, in get
    return deserialize(config)
  File "c:\users\adr\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\keras\optimizers.py", line 790, in deserialize
    printable_module_name='optimizer')
  File "c:\users\adr\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py", line 175, in deserialize_keras_object
    return cls.from_config(config['config'])
  File "c:\users\adr\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\keras\optimizers.py", line 149, in from_config
    return cls(**config)
  File "c:\users\adr\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\keras\optimizers.py", line 445, in __init__
    self.iterations = K.variable(0, dtype='int64', name='iterations')
  File "c:\users\adr\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\keras\backend.py", line 648, in variable
    constraint=constraint)
  File "c:\users\adr\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 312, in __init__
    constraint=constraint)
  File "c:\users\adr\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 470, in _init_from_args
    gen_resource_variable_ops.var_is_initialized_op(self._handle))
  File "c:\users\adr\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\ops\gen_resource_variable_ops.py", line 1455, in var_is_initialized_op
    "VarIsInitializedOp", resource=resource, name=name)
  File "c:\users\adr\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "c:\users\adr\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\util\deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "c:\users\adr\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\framework\ops.py", line 3155, in create_op
    op_def=op_def)
  File "c:\users\adr\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\framework\ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Cannot assign a device for operation 'Adam_1/iterations/IsInitialized/VarIsInitializedOp': Could not satisfy explicit device specification '' because the node was colocated with a group of nodes that required incompatible device '/device:GPU:1'
Colocation Debug Info:
Colocation group had the following types and devices: 
VarHandleOp: CPU 
AssignVariableOp: CPU 
VarIsInitializedOp: CPU 
ReadVariableOp: CPU 
AssignAddVariableOp: CPU 

Colocation members and user-requested devices:
  Adam_1/iterations (VarHandleOp) 
  Adam_1/iterations/IsInitialized/VarIsInitializedOp (VarIsInitializedOp) 
  Adam_1/iterations/Assign (AssignVariableOp) 
  Adam_1/iterations/Read/ReadVariableOp (ReadVariableOp) 
  training_1/Adam/AssignAddVariableOp (AssignAddVariableOp) /device:GPU:1
  training_1/Adam/ReadVariableOp (ReadVariableOp) /device:GPU:1
  training_1/Adam/Cast/ReadVariableOp (ReadVariableOp) 
  VarIsInitializedOp_21 (VarIsInitializedOp) /device:GPU:1

	 [[Node: Adam_1/iterations/IsInitialized/VarIsInitializedOp = VarIsInitializedOp[](Adam_1/iterations)]]
